apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8501
    protocol: TCP
  selector:
    app: streamlit-app